Working with javascript/built in helpers
campuscode/rails-guides-pt-BR pull request #316
Opened 2020-08-03 15:57 UTC by oliveira-andre

Close: *https://github.com/campuscode/rails-guides-pt-BR/issues/315*

## Motivação

Amo rails e amo javascript e cada vez mais ele tem se mostrado muito bom ao lado desse incrivel framework, e recentemente o criador do Go Rails postou um video muito interessante sobre como fazer um infinite scroll na pagina, paginando ela e fazendo requisições ajax, e muita gente se viu refem novamente do inglês, e com esse conhecimento de ajax mais aprofundado através dessa documentação talvez ajude muitas pessoas a conseguirem executar o código sem simplesmente copiar e colar.
Exemplo:

Tradução do tópico  **3 built-in helpers** da página **Working with javascript.**.

## Comentários

traduzi apenas o segundo capitulo que é built-in helpers

https://guides.rubyonrails.org/working_with_javascript_in_rails.html#built-in-helpers

2020-09-30 03:20 UTC, marivaldo requested changes

2020-09-30 03:20 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +na criação do HTML. as vezses, você quer adicionar um pouco de *Ajax* para esses elementos,
```suggestion
na criação do HTML. As vezses, você quer adicionar um pouco de *Ajax* para esses elementos,
```

2020-09-30 03:29 UTC, marivaldo requested changes

2020-09-30 03:29 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +Vamos assumir que nós temos um lista de artigos que podem ser deletadas com apenas
```suggestion
Vamos assumir que nós temos uma lista de artigos que podem ser deletadas com apenas
```

2020-09-30 03:38 UTC, marivaldo requested changes

2020-09-30 03:38 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +Uma vez que é apenas um `<form>`, todas as informações do `form_withh` também se aplicam.
```suggestion
Uma vez que é apenas um `<form>`, todas as informações do `form_with` também se aplicam.
```

2020-09-30 03:42 UTC, marivaldo requested changes

2020-09-30 03:42 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +O modo coom isso funciona é que, quando um link é ativado, ele constrói um formulário
```suggestion
O modo como isso funciona é que, quando um link é ativado, ele constrói um formulário
```

2020-09-30 03:45 UTC, marivaldo requested changes

2020-09-30 03:45 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +que eles acionem chamadas Ajax. Especificando o o atributo `data-url` juntamente com o `data-remote`
```suggestion
que eles acionem chamadas Ajax. Especificando o atributo `data-url` juntamente com o `data-remote`
```

2020-09-30 03:47 UTC, marivaldo requested changes

2020-09-30 03:47 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +especificar parametros extras através do atributo `data-params`.
```suggestion
especificar parâmetros extras através do atributo `data-params`.
```

2020-09-30 03:57 UTC, marivaldo requested changes

2020-09-30 03:57 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +Adicionando esse atributo nos links disparará a mensagem no clique, e adicionando
```suggestion
Adicionando esse atributo nos links, será disparado a mensagem no clique, e adicionando
```

2020-09-30 03:57 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +aos formulários disparará no *submit*. Por exemplo:
```suggestion
aos formulários, será disparado no *submit*. Por exemplo:
```

2020-09-30 04:01 UTC, marivaldo requested changes

2020-09-30 04:01 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +gerenciador de confirmação retorne *false*.
```suggestion
gerenciador de confirmação retornar *false*.
```

2020-09-30 04:05 UTC, marivaldo requested changes

2020-09-30 04:05 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +Também é possível disabilitar automaicamente um input enquanto o formuário está sendo
```suggestion
Também é possível desabilitar automaicamente um input enquanto o formuário está sendo
```

2020-09-30 04:15 UTC, marivaldo requested changes

2020-09-30 04:15 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +Nesse parâmetro, existe um atributo adicional o `detail` o qual contém um *array* de parametros extra.
```suggestion
Nesse parâmetro, existe um atributo adicional, o `detail`, ao qual contém um *array* de parametros extra.
```

2020-09-30 04:15 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A partir do Rails 5.1 e o novo `rails-ujs`, os parametros `data, status, xhr`
```suggestion
OBSERVAÇÃO: A partir do Rails 5.1 e o novo `rails-ujs`, os parâmetros `data, status, xhr`
```

2020-10-01 14:32 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Uma vez que é apenas um `<form>`, todas as informações do `form_withh` também se aplicam.
valeu, resolvido!

2020-10-01 14:32 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +que eles acionem chamadas Ajax. Especificando o o atributo `data-url` juntamente com o `data-remote`
valeu, resolvido!

2020-10-01 14:32 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Adicionando esse atributo nos links disparará a mensagem no clique, e adicionando
valeu, resolvido!

2020-10-01 14:32 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +gerenciador de confirmação retorne *false*.
valeu, resolvido!

2020-10-01 14:32 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Nesse parâmetro, existe um atributo adicional o `detail` o qual contém um *array* de parametros extra.
valeu, resolvido!

2020-10-01 14:32 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A partir do Rails 5.1 e o novo `rails-ujs`, os parametros `data, status, xhr`
valeu, resolvido!

2020-10-01 14:33 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Também é possível disabilitar automaicamente um input enquanto o formuário está sendo
valeu, resolvido!

2020-10-01 14:33 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +aos formulários disparará no *submit*. Por exemplo:
valeu, resolvido!

2020-10-01 14:33 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +especificar parametros extras através do atributo `data-params`.
valeu, resolvido!

2020-10-01 14:33 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +O modo coom isso funciona é que, quando um link é ativado, ele constrói um formulário
valeu, resolvido!

2020-10-01 14:33 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Vamos assumir que nós temos um lista de artigos que podem ser deletadas com apenas
valeu, resolvido!

2020-10-03 21:13 UTC, HenriqueMorato reviewed
Yay! Parabéns por mais essa contribuição 🎉 

Fiz algumas sugestões e na maioria delas tentei deixar uma suggestion pra facilitar mas fique bem a vontade para responder, aprovar ou declinar.

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +Veja o `data-remote="true"`. Agora, o formulário será enviado por ajax ao invés
```suggestion
Veja o `data-remote="true"`. Agora, o formulário será enviado por *Ajax* ao invés
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +sua aplicação é [RESTful](https://en.wikipedia.org/wiki/Representational_State_Transfer),
```suggestion
sua aplicação é [RESTful](https://pt.wikipedia.org/wiki/REST),
```

Achei a página em português bem completa, acha que podemos linkar aqui?

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +link, e o método corresponde ao valor do `data-method`, e envia esse forumlário.
```suggestion
link, e o método corresponde ao valor do `data-method`, e envia esse formulário.
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: por causa dos envios de formulários com outros métodos HTTP além de
```suggestion
NOTE: por causa dos envios de formulários com outros métodos HTTP além de
```

Esses aqui não precisa traduzir, eles são uma marcação que o Guides usa pra criar um ícone na hora de gerar a página 😄 

É estranho eu sei mas funciona hahaha

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +GET e POST não são ampalmente suportados entre navegadores, todos os outros métodos
```suggestion
GET e POST não são amplamente suportados entre navegadores, todos os outros métodos
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +Também é possível desabilitar automaicamente um input enquanto o formuário está sendo
```suggestion
Também é possível desabilitar automaticamente um input enquanto o formulário está sendo
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +Rails 5.1 introduziu o `rails-ujs` e removeram o jQquery como dependência.
```suggestion
Rails 5.1 introduziu o `rails-ujs` e removeram o jQuery como dependência.
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A assinatura de chamadas para os manipuladores de eventos do `UJS` mudaram.
```suggestion
NOTE: A assinatura de chamadas para os manipuladores de eventos do `UJS` mudaram.
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +Diferente da versão com *jQuery*, todos os eventos personalizados retornam apenas um parametro: `event`.
```suggestion
Diferente da versão com jQuery, todos os eventos personalizados retornam apenas um parâmetro: `event`.
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +| Nome do evento      | Parametros extra (event.detail) | Quando é executado                                          |
```suggestion
| Nome do evento      | Parâmetros extras (event.detail) | Quando é executado                                          |
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A partir do Rails 5.1 e o novo `rails-ujs`, os parâmetros `data, status, xhr`
```suggestion
NOTE: A partir do Rails 5.1 e o novo `rails-ujs`, os parâmetros `data, status, xhr`
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +que o navegador envie o formulário por meios normais (*i.e. non-Aja submission*)
```suggestion
que o navegador envie o formulário por meios normais (i.e. requisição sem Ajax)
```

Acho que aqui pode traduzir mesmo e deixa o `i.e.` do latim o que acha?

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +que o navegador envie o formulário por meios normais (*i.e. non-Aja submission*)
O @akaninja manja mais dessa parte. Pode dar uma olhada?

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +será cancelada e o fomulário não será enviado de nenhuma forma. Isso é útil para
```suggestion
será cancelada e o formulário não será enviado de nenhuma forma. Isso é útil para
```

2020-10-03 21:13 UTC, HenriqueMorato commented on pt-BR/working_with_javascript_in_rails.md
> +Observação, você deveria usar o `return false` para previnir eventos para o `jquery-ujs`
```suggestion
Observação, você deveria usar o `return false` para prevenir eventos para o `jquery-ujs`
```

2020-10-04 16:54 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +A não ser que você desabilite o *Asse Pipeline*,
boa! arrumei.

2020-10-04 16:54 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +fornece a metade JavaScript, e os regulares *view helpers* Ruby adicionam as *tags* apropriadas
boa! arrumei.

2020-10-04 16:54 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Veja o `data-remote="true"`. Agora, o formulário será enviado por ajax ao invés
boa! arrumei.

2020-10-04 16:54 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +sua aplicação é [RESTful](https://en.wikipedia.org/wiki/Representational_State_Transfer),
boa! arrumei.

2020-10-04 16:55 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +link, e o método corresponde ao valor do `data-method`, e envia esse forumlário.
boa! arrumei.

2020-10-04 16:55 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: por causa dos envios de formulários com outros métodos HTTP além de
boa!! resolvido

2020-10-04 16:56 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +GET e POST não são ampalmente suportados entre navegadores, todos os outros métodos
boa! arrumei.

2020-10-04 16:56 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Também é possível desabilitar automaicamente um input enquanto o formuário está sendo
boa! arrumei.

2020-10-04 16:57 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Rails 5.1 introduziu o `rails-ujs` e removeram o jQquery como dependência.
boa! arrumei.

2020-10-04 16:58 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A assinatura de chamadas para os manipuladores de eventos do `UJS` mudaram.
boa! arrumei.

2020-10-04 16:58 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Diferente da versão com *jQuery*, todos os eventos personalizados retornam apenas um parametro: `event`.
boa! arrumei.

2020-10-04 16:58 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +| Nome do evento      | Parametros extra (event.detail) | Quando é executado                                          |
boa! arrumei.

2020-10-04 16:59 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A partir do Rails 5.1 e o novo `rails-ujs`, os parâmetros `data, status, xhr`
boa! arrumei.

2020-10-04 16:59 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +que o navegador envie o formulário por meios normais (*i.e. non-Aja submission*)
boa! arrumei.

2020-10-04 16:59 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +será cancelada e o fomulário não será enviado de nenhuma forma. Isso é útil para
boa! arrumei.

2020-10-04 17:00 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +Observação, você deveria usar o `return false` para previnir eventos para o `jquery-ujs`
boa! arrumei.

2020-10-05 15:38 UTC, marivaldo commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A partir do Rails 5.1 e do novo `rails-ujs`, os parâmetros
```suggestion
NOTE: A partir do Rails 5.1 e do novo `rails-ujs`, os parâmetros
```
seguindo o que já foi mantido.

2020-10-05 17:27 UTC, oliveira-andre commented on pt-BR/working_with_javascript_in_rails.md
> +OBSERVAÇÃO: A partir do Rails 5.1 e do novo `rails-ujs`, os parâmetros
boa! feito!!

2020-10-05 18:13 UTC, HenriqueMorato approved these changes

2020-10-05 20:34 UTC, marivaldo approved these changes

2020-10-07 16:31 UTC, merged

2020-10-07 17:20 UTC, HenriqueMorato commented
Já está disponível no [guiarails](https://www.guiarails.com.br/working_with_javascript_in_rails.html#helpers-internos) 🚀 🎉