Active Record Query Interface > 2. Conditions
campuscode/rails-guides-pt-BR pull request #371
Opened 2020-10-22 19:10 UTC by LukasPol

Close: #148
Motivação

Tradução do tópico 2. Conditions da página Active Record Query Interface.
Comentários

https://guides.rubyonrails.org/active_record_querying.html#conditions

Traduzir só o segundo tópico completo (Conditions)

2020-10-23 16:31 UTC, akaninja requested changes
Olá, obrigado pela contribuição! :)

Fiz algumas correções e sugestões. Veja o que acha...

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +WARNING: Construindo sua própria condição como strings pura pode te deixar vulnerável a façanha de injeção SQL. Por exemplo, `Client.where("first_name LIKE '%#{params[:first_name]}%'")` não é seguro.
Achei que "façanhas" como tradução para "exploit" ficou um pouco fora do contexto. Fiz uma sugestão...

```suggestion
WARNING: Construindo sua própria condição como *string* pura pode te deixar vulnerável a ataques de injeção SQL. Por exemplo, `Client.where("first_name LIKE '%#{params[:first_name]}%'")` não é seguro. Veja a próxima seção para a maneira de lidar com condições usando *array*.
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Agora, se esse número pudesse variar, digamos como um argumento de algum lugar? O achado então levaria a forma:
```suggestion
Agora, se esse número pudesse variar, digamos como um argumento de algum lugar? O comando da busca então levaria a forma:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Active Record tomará o primeiro argumento como a string de condições e quaisquer argumento adicional vai substituir os pontos de interrogação `(?)` nele.
```suggestion
*Active Record* tomará o primeiro argumento como a *string* de condições e quaisquer argumentos adicionais vão substituir os pontos de interrogação `(?)` nele.
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Se você quer especificar muiltiplas condições:
```suggestion
Se você quer especificar múltiplas condições:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Por causa da segurança do argumento. Colocando a variável dentro da condição de string parará a variable para o banco de dados **como se encontra**. Isto significa que isso será uma variável sem esca
```suggestion
devido à segurança do argumento. Colocando a variável dentro da condição de *string*, passará a variável para o banco de dados **como se encontra**. Isto significa que será uma variável sem escape diretamente de um usuário que pode ter intenções maliciosas. Se você fizer isso, coloca todo seu banco de dados em risco, porque uma vez que um usuário descobre que pode explorar seu banco de dados, ele pode fazer qualquer coisa com ele. Nunca, jamais, coloque seus argumentos diretamente dentro da condição de *string*.
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +TIP: Para mais informações sobre os perigos  da injeção de SQL, veja em [Ruby on Rails Security Guide](https://guides.rubyonrails.org/security.html#sql-injection) / [Ruby on Rails Security Guide PT-B
```suggestion
TIP: Para mais informações sobre os perigos da injeção de SQL, veja em [Ruby on Rails Security Guide](https://guides.rubyonrails.org/security.html#sql-injection) / [Ruby on Rails Security Guide PT-Br](security.html#sql-injection)
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Similar ao estilo de substituição `(?)` dos parâmetros, você também pode especificar chaves em sua condição de string junto com um hash de chaves/valores(keys/values) correspondentes:
```suggestion
Similar ao estilo de substituição `(?)` dos parâmetros, você também pode especificar chaves em sua condição de *string* junto com uma *hash* de chaves/valores (*keys/values*) correspondentes:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Active Record também permite que você passe em condições de hash o que pode aumentar a legibilidade de suas sintaxes de condições. Com condições de hash, você passa em uma hash com chaves(keys) dos c
```suggestion
*Active Record* também permite que você passe em condições de *hash* o que pode aumentar a legibilidade de suas sintaxes de condições. Com condições de *hash*, você passa em uma *hash* com chaves (*keys*) dos campos que deseja qualificados e os valores (*values*) de como deseja qualificá-los:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +NOTE: Apenas igualdade, intervalo, e subconjunto são possiveis com as condições de hash.
```suggestion
NOTE: Apenas igualdade, intervalo, e subconjunto são possiveis com as condições de *hash*.
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +O nome do campo também pode ser uma string:
```suggestion
O nome do campo também pode ser uma *string*:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Isso irá encontrar todos clientes criado ontem usando uma instrução SQL `BETWEEN`:
```suggestion
Isso irá encontrar todos clientes criados ontem usando uma instrução SQL `BETWEEN`:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Essa demonstração uma sintaxe mais curta para examplos em [Condições de Array](#condiçoes-de-array)
```suggestion
Isso demonstra uma sintaxe mais curta para exemplos em [Condições de Array](#condiçoes-de-array)
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Se você deseja procurar registros usando a expressão `IN` pode passar uma array para o hash de condições:
```suggestion
Se você deseja procurar registros usando a expressão `IN` pode passar um *array* para a *hash* de condições:
```

2020-10-23 16:31 UTC, akaninja commented on pt-BR/active_record_querying.md
> +Isso código irá gerar um SQL como este:
```suggestion
Esse código irá gerar um SQL como este:
```

2020-10-23 20:24 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Isso código irá gerar um SQL como este:
Corrigido

2020-10-23 20:24 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Se você deseja procurar registros usando a expressão `IN` pode passar uma array para o hash de condições:
Corrigido

2020-10-23 20:24 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Essa demonstração uma sintaxe mais curta para examplos em [Condições de Array](#condiçoes-de-array)
Corrigido

2020-10-23 20:25 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Isso irá encontrar todos clientes criado ontem usando uma instrução SQL `BETWEEN`:
Corrigido

2020-10-23 20:25 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +O nome do campo também pode ser uma string:
Corrigido

2020-10-23 20:26 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +O método `where`  permite que você especifique condições para limitar os registro retornados, representando o `where`-part da instrução SQL. Condições podem ser especificado como uma string, array(li
Corrigido

2020-10-23 20:26 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +WARNING: Construindo sua própria condição como strings pura pode te deixar vulnerável a façanha de injeção SQL. Por exemplo, `Client.where("first_name LIKE '%#{params[:first_name]}%'")` não é seguro.
Corrigido

2020-10-23 20:28 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Agora, se esse número pudesse variar, digamos como um argumento de algum lugar? O achado então levaria a forma:
Corrigido

2020-10-23 20:28 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Active Record tomará o primeiro argumento como a string de condições e quaisquer argumento adicional vai substituir os pontos de interrogação `(?)` nele.
Corrigido

2020-10-23 20:28 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Se você quer especificar muiltiplas condições:
Corrigido

2020-10-23 20:29 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +TIP: Para mais informações sobre os perigos  da injeção de SQL, veja em [Ruby on Rails Security Guide](https://guides.rubyonrails.org/security.html#sql-injection) / [Ruby on Rails Security Guide PT-B
Corrigido

2020-10-23 20:30 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Active Record também permite que você passe em condições de hash o que pode aumentar a legibilidade de suas sintaxes de condições. Com condições de hash, você passa em uma hash com chaves(keys) dos c
Corrigidos

2020-10-23 20:30 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +NOTE: Apenas igualdade, intervalo, e subconjunto são possiveis com as condições de hash.
Corrigido

2020-10-23 20:31 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Se você gostaria de adicionar condições para sua procura, você poderia apenas especifica-los lá, somente como `Client.where("orders_count = '2'")`. Isso encontrará todos os clientes onde o campo `ord
Corrigido

2020-10-23 20:32 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Por causa da segurança do argumento. Colocando a variável dentro da condição de string parará a variable para o banco de dados **como se encontra**. Isto significa que isso será uma variável sem esca
Corrigido

2020-10-23 20:32 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Similar ao estilo de substituição `(?)` dos parâmetros, você também pode especificar chaves em sua condição de string junto com um hash de chaves/valores(keys/values) correspondentes:
Corrigido

2020-10-23 20:33 UTC, LukasPol commented
Creio q tudo está resolvido, obrigado pelos toques tomarei mais cuidado na próxima!

2020-10-23 20:34 UTC, LukasPol commented
E sobre o outro PR, não consegui atualizar aquele, tive que abrir um outro :(

2020-10-23 21:34 UTC, HenriqueMorato reviewed
Parabéns pela contribuição 👏 

Deixei algumas sugestões pode dar uma olhada 😄

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +#### Placeholder na condição
```suggestion
#### Condições com *Placeholder*
```

Aqui fiquei um pouco na dúvida mas seria legal mantermos o mesmo estilo do título anterior, acha que faz sentido?

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +Isso torna a legibilidade mais clara se você tem um grande número de condições variaveis.
```suggestion
Isso torna a legibilidade mais clara se você tem um grande número de condições variáveis.
```

Aqui acho que tem um typo, pode dar uma olhada?

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +NOTE: Apenas igualdade, intervalo, e subconjunto são possiveis com as condições de *hash*.
```suggestion
NOTE: Apenas igualdade, intervalo, e subconjunto são possíveis com as condições de *hash*.
```

Aqui acho que ficou um typo, pode dar uma olhada?

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +No caso de um relacionamento `belongs_to`, uma chave de associação pode ser usada para especificar o model se um objeto Active Record for usado como o valor. Este metodo também funciona com relaciona
```suggestion
No caso de um relacionamento `belongs_to`, uma chave de associação pode ser usada para especificar o model se um objeto Active Record for usado como o valor. Este método também funciona com relacionamentos polimórficos.
```

Aqui acho que ficou um typo, pode dar uma olhada?

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +Isso demonstra uma sintaxe mais curta para exemplos em [Condições de Array](#condiçoes-de-array)
```suggestion
Isso demonstra uma sintaxe mais curta para exemplos em [Condições de Array](#condicoes-de-array)
```

Os links perdem os caracteres especiais então deixei a sugestão de como vai ficar 😄

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +Consultas SQL `NOT` podem ser construidas por `where.not`:
```suggestion
Consultas SQL `NOT` podem ser construídas por `where.not`:
```

Aqui acho que ficou um typo, pode dar uma olhada?

2020-10-23 21:34 UTC, HenriqueMorato commented on pt-BR/active_record_querying.md
> +Condições `OR` entre duas relações podem ser construidas chamando `or` na primeira relação, e passando o segundo como um argumento.
```suggestion
Condições `OR` entre duas relações podem ser construídas chamando `or` na primeira relação, e passando o segundo como um argumento.
```

Aqui acho que ficou um typo, pode dar uma olhada?

2020-10-26 17:11 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +#### Placeholder na condição
Siim, ficou bem melhor kkk

2020-10-26 17:13 UTC, LukasPol commented on pt-BR/active_record_querying.md
> +Isso demonstra uma sintaxe mais curta para exemplos em [Condições de Array](#condiçoes-de-array)
Vdd, deixei sem o `~` no `O`, mas esqueci do `ç`, vlw

2020-10-26 17:27 UTC, LukasPol commented
Finalizadas as novas sugestões

2020-10-26 21:26 UTC, HenriqueMorato approved these changes

2020-10-27 03:23 UTC, tkusuki approved these changes
:top:

2020-10-27 15:06 UTC, merged

2020-10-27 15:16 UTC, HenriqueMorato commented
Já está disponível no [Guia Rails](https://www.guiarails.com.br/active_record_querying.html#condicoes) 🎉