Active Job Basics > 2. The Purpose of Active Job
campuscode/rails-guides-pt-BR pull request #398
Opened 2020-10-24 03:35 UTC by MarcusAldrey

closes #386

## Motivação

Tradução do tópico 2. The Purpose of Active Job da página Active Job Basics.

2020-10-24 04:29 UTC, MarcusAldrey commented
Os vários commits foram para corrigir alguns problemas que tive com as branches

2020-10-25 00:56 UTC, HenriqueMorato reviewed
Parabéns pela contribuição @MarcusAldrey 

Fiz alguns comentários pode dar uma olhada? Fique a vontade para responder, aprovar ou descartar 😄

2020-10-25 00:56 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +O propósito do Active Job
```suggestion
O Propósito do Active Job
````

Será que faz sentido manter em maiúsculo 🤔 

O que acha @MarcusAldrey ?

2020-10-25 00:56 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +contruídas em cima dela, sem ter que nos preocupar com diferenças de API entre vários
```suggestion
construídas em cima dela, sem ter que nos preocupar com diferenças de API entre vários
```

Acho que aqui ficou um typo pode dar uma olhada?

2020-10-25 00:56 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +NOTA: Rails por padrão vem com uma implementação de fila assíncrona que executa *jobs*
```suggestion
NOTE: Rails por padrão vem com uma implementação de fila assíncrona que executa *jobs*
```

Essas palavras que ficam todas em maiúsculas como "NOTE", "WARNING", etc são importante manter porque elas ajudam a gerar HTML. É bem estranho eu sei, mas é o jeito do Rails haha 🤷

2020-10-25 00:57 UTC, HenriqueMorato commented
> Os vários commits foram para corrigir alguns problemas que tive com as branches

Não tem problema a gente costuma fazer squash dos commits antes de fazer o merge 😄

2020-10-25 01:10 UTC, MarcusAldrey commented
olhei e concordo com as alterações sugeridas, realizei os commits

2020-10-27 02:37 UTC, tkusuki approved these changes

2020-10-27 15:03 UTC, HenriqueMorato approved these changes

2020-10-27 15:04 UTC, HenriqueMorato commented
Oi, @MarcusAldrey tudo bem?

Deram alguns conflitos nesse branch, você consegue resolver aí? É só aceitar as traduções que foram feitas por você no tópico 1. :)

Se precisar de ajuda me avise.

2020-10-27 19:37 UTC, MarcusAldrey commented
feito

2020-10-27 21:05 UTC, HenriqueMorato requested changes
Oi, @MarcusAldrey , tudo bem?

Alguns conflitos acho que voltaram pro inglês. Tentei colocar sugestões pra facilitar, pode dar uma olhada?

2020-10-27 21:05 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +enqueuing and executing background jobs.
```suggestion
Este guia oferece a você tudo o que você precisa para começar a criar, enfileirar e executar *jobs* em *background*
```

2020-10-27 21:05 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +After reading this guide, you will know:
```suggestion
Depois de ler este guia, você saberá:
```

2020-10-27 21:05 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +* How to send emails from your application asynchronously.
```suggestion
* Como criar *jobs*
* Como enfileirar *jobs*
* como executar *jobs* em segundo plano 
* Como enviar emails de sua aplicação de maneira assíncrona 
```

2020-10-27 21:05 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +Introduction
```suggestion
Introdução 
```

2020-10-27 23:25 UTC, MarcusAldrey commented
pronto

2020-10-27 23:49 UTC, HenriqueMorato approved these changes

2020-10-27 23:49 UTC, merged

2020-10-28 15:11 UTC, HenriqueMorato commented
Já está disponível no Guia Rails 🎉 🚀