Active Job Basics > 6. Callbacks
campuscode/rails-guides-pt-BR pull request #399
Opened 2020-10-24 12:55 UTC by rafael-acerqueira

Close: #390 

## Motivação

Tradução do tópico  **6 Callbacks** da página **Active Job Basics**.

## Comentários

https://guides.rubyonrails.org/active_job_basics.html#callbacks

2020-10-24 16:50 UTC, maugravena requested changes
Muito bom @rafael-acerqueira, fiz apenas algumas sugestões caso faça sentido.

2020-10-24 16:50 UTC, maugravena commented on pt-BR/active_job_basics.md
> +O *Active Job* fornce Hooks para disparar lógica durante o ciclo de vida de um *Job*.
```suggestion
O *Active Job* fornece Hooks para disparar lógica durante o ciclo de vida de um *Job*.
```

2020-10-24 16:50 UTC, maugravena commented on pt-BR/active_job_basics.md
> +como métodos ordinários e usar um método macro de classe para registrá-los
```suggestion
como métodos comuns e usar um método macro de classe para registrá-los
```

2020-10-24 20:38 UTC, rafael-acerqueira commented on pt-BR/active_job_basics.md
> +O *Active Job* fornce Hooks para disparar lógica durante o ciclo de vida de um *Job*.
Boa

2020-10-24 20:40 UTC, rafael-acerqueira commented on pt-BR/active_job_basics.md
> +como métodos ordinários e usar um método macro de classe para registrá-los
Opa, me passei ai. Obrigado :+1:

2020-10-25 01:03 UTC, HenriqueMorato reviewed
Parabéns pela contribuição @rafael-acerqueira 👏 

Fiz alguns comentários pode dar uma olhada.

Uma coisa que vi mas não consegui fazer sugestão porque o GitHub não deixou 😢 

É que abaixo ficou faltando traduzir o título `Available callbacks` pode dar uma olhada?

2020-10-25 01:03 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +
```suggestion
```

Acho que essa linha não é necessária, será que podemos removê-la?

2020-10-25 01:03 UTC, HenriqueMorato commented on pt-BR/active_job_basics.md
> +se o código dentro do bloco for tão pequeno que cabe  numa única linha.
```suggestion
se o código dentro do bloco for tão pequeno que cabe numa única linha.
```

Acho que aqui ficou um espaço a mais, pode dar uma olhada?

2020-10-25 09:17 UTC, rafael-acerqueira commented on pt-BR/active_job_basics.md
> +
Boa

2020-10-25 09:18 UTC, rafael-acerqueira commented on pt-BR/active_job_basics.md
> +se o código dentro do bloco for tão pequeno que cabe  numa única linha.
É mesmo :grimacing: . Ajustei

2020-10-26 13:47 UTC, HenriqueMorato approved these changes

2020-10-27 02:38 UTC, tkusuki approved these changes
:top:

2020-10-27 15:04 UTC, merged

2020-10-27 15:19 UTC, HenriqueMorato commented
Já está disponível no [Guia Rails](https://www.guiarails.com.br/active_job_basics.html#callbacks) 🎉 🚀