Translate webpacker introduction
campuscode/rails-guides-pt-BR pull request #747
Opened 2022-10-01 16:09 UTC by laurasantiagocm

Close: [746](https://github.com/campuscode/rails-guides-pt-BR/issues/746)
## Motivação

*Descreva as motivações deste PR*

Exemplo:

Tradução do tópico  **1 O que é webpack?** e da introdução  da página **Webpacker**.

2022-10-01 18:11 UTC, tomascco requested changes
Parabéns pela contribuição 😄, fiz uma revisão e acho que encontrei alguns erros de digitação.

2022-10-01 18:11 UTC, tomascco commented on pt-BR/webpacker.md
> +Esse guia irá mostrar como instalar e usar o Webpacker para enpacotar JavaScript, CSS e outros *assets* para a lado cliente da sua aplicação Rails.
```suggestion
Esse guia irá mostrar como instalar e usar o Webpacker para empacotar JavaScript, CSS e outros *assets* para a lado cliente da sua aplicação Rails.
```

2022-10-01 18:11 UTC, tomascco commented on pt-BR/webpacker.md
> +* Como fazer deploy com uma aplicação que usa Webpacker.
```suggestion
* Como fazer deploy de uma aplicação que usa Webpacker.
```

2022-10-01 18:11 UTC, tomascco commented on pt-BR/webpacker.md
> +* Como usar o Webpacker em contextos alternativos de Rails, como *engines* ou *containers* Docker.
```suggestion
* Como usar o Webpacker em contextos Rails alternativos, como *engines* ou *containers* Docker.
```

2022-10-01 18:11 UTC, tomascco commented on pt-BR/webpacker.md
> +Você deve escolher Webpacker em vez de Sprockets em um projeto novo se quiser utulizar pacotes NPM e/ou quiser acessar features e ferramentas mais atuais de Javascript. Você deve escolher Sprockets e
```suggestion
Você deve escolher Webpacker em vez de Sprockets em um projeto novo se quiser utulizar pacotes NPM e/ou quiser acessar features e ferramentas mais atuais de Javascript. Você deve escolher Sprockets em vez de Webpacker para aplicações legado onde migrações podem ser custosas, se você quiser integrar usando Gems ou se tiver uma quantidade pequena de código a ser empacotado.
```

2022-10-01 18:11 UTC, tomascco commented on pt-BR/webpacker.md
> +|Requirir um *script* |//= require           |import or require  |
```suggestion
|Requerer um *script* |//= require           |import or require  |
```

2022-10-01 18:38 UTC, laurasantiagocm commented on pt-BR/webpacker.md
> +Esse guia irá mostrar como instalar e usar o Webpacker para enpacotar JavaScript, CSS e outros *assets* para a lado cliente da sua aplicação Rails.
boa! obrigada por todas as sugestões

2022-10-07 02:16 UTC, tkusuki reviewed
Excelente contribuição @laurasantiagocm! :tada: 

Fiz apenas algumas sugestões e também correção de uns typos.
Pode validar? :smile:

2022-10-07 02:16 UTC, tkusuki commented on pt-BR/webpacker.md
> +* Como instalar o Webpacker e integrar com seu framework de escolha.
```suggestion
* Como instalar o Webpacker e integrar com seu _framework_ de escolha.
```

2022-10-07 02:16 UTC, tkusuki commented on pt-BR/webpacker.md
> +O intuito do webpack, ou qualquer sistema de *build* front-end, é permitir que você escreva código front-end de maneira coveniente para desenvolvedores e depois empacotar o código de maneira covenien
```suggestion
O intuito do webpack, ou qualquer sistema de *build* front-end, é permitir que você escreva código front-end de maneira conveniente para pessoas desenvolvedoras e depois empacotar o código de maneira conveniente para navegadores. Com o webpack, você pode gerenciar Javascript, CSS e *assets* estáticos, como imagens e fontes. O webpack permite que você escreva seu código, referencie outro código na aplicação, transforme seu código e combine ele em pacotes que podem ser facilmente baixados.
```

2022-10-07 02:16 UTC, tkusuki commented on pt-BR/webpacker.md
> +O Rails também funciona com o Sprockets, uma ferramenta de enpacotamento de *assets* que tem algumas features em comum com o Webpacker. Ambas vão compilar seu Javascript em arquivos "amigáveis" para
```suggestion
O Rails também funciona com o Sprockets, uma ferramenta de empacotamento de *assets* que tem algumas funcionalidade em comum com o Webpacker. Ambas vão compilar seu Javascript em arquivos "amigáveis" para o navegador, além de minificar e adicionar *fingerprints* neles em produção. Em ambiente de desenvolvimento, o Sprockets e o Webpacker permitem que você altere arquivos de maneira incremental.
```

2022-10-07 02:16 UTC, tkusuki commented on pt-BR/webpacker.md
> +Você deve escolher Webpacker em vez de Sprockets em um projeto novo se quiser utulizar pacotes NPM e/ou quiser acessar features e ferramentas mais atuais de Javascript. Você deve escolher Sprockets e
```suggestion
Você deve escolher o Webpacker em vez de Sprockets em um projeto novo se quiser utilizar pacotes NPM e/ou quiser acessar funcionalidades e ferramentas mais atuais de Javascript. Você deve escolher o Sprockets em vez do Webpacker para aplicações legadas onde migrações podem ser custosas, se você quiser integrar usando Gems ou se tiver uma quantidade pequena de código a ser empacotado.
```

2022-10-07 02:16 UTC, tkusuki commented on pt-BR/webpacker.md
> +Se você for familiar com o Sprockets, o guia a seguir pode trazer ideias de correspondência entre as duas ferramentas. Por favor, note que cada ferramenta tem uma estrutura diferente, e os conceitos
```suggestion
Se você estiver familiarizado com o Sprockets, o guia a seguir pode trazer ideias de correspondência entre as duas ferramentas. Por favor, note que cada ferramenta tem uma estrutura diferente, e os conceitos não são exatamentes iguais um ao outro.
```

2022-10-11 21:25 UTC, tkusuki approved these changes
:rocket:

2022-10-12 13:42 UTC, HenriqueMorato commented
@laurasantiagocm você consegue fazer `pull` da `main` novamente e mudar o comecinho novamente pra resolver o conflito? Eu também posso requisitar acesso e resolver se você quiser 😄

2022-10-23 14:58 UTC, merged