Traduzir página Maintenance Policy
campuscode/rails-guides-pt-BR pull request #749
Opened 2022-10-01 16:57 UTC by laurasantiagocm

Close: [748](https://github.com/campuscode/rails-guides-pt-BR/issues/748)

## Motivação

Tradução da página **Maintenance Policy**.

## Comentários

Estava em dúvida se usava "lançamento" ou "release". Coloquei "lançamento" pois vi que algumas traduções usavam ela.

2022-10-01 17:57 UTC, HenriqueMorato reviewed
Yay! Parabéns pela primeira contribuição.

Fiz algumas sugestões de itálicos e espaços, fique a vontade para discordar ou não usar.

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +***Patch* `Z`**
```suggestion
**_Patch_ `Z`**
```

Acho que aqui talvez seja melhor usar outro símbolo para evitar problemas na geração futura, o que acha?

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +***Minor* `Y`**
```suggestion
**_Minor_ `Y`**
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +A diferença entre as lançamentos *minor* e *major* do Rails é a magnitude das mudanças significativas, e geralmente para ocasições especiais.
```suggestion
A diferença entre as lançamentos *minor* e *major* do Rails é a magnitude das mudanças significativas, e geralmente para ocasiões especiais.
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +Novas features são adicionadas apenas na branch principal e não estarão disponíveis em lançamentos pontuais.
```suggestion
Novas funcionalidades são adicionadas apenas na *branch* principal e não estarão disponíveis em lançamentos pontuais.
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +Novas Features
```suggestion
Novas Funcionalidades
```

Apesar de `features` ser uma palavra comum aqui podemos usar a palavra funcionalidades se achar legal.

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +Correções de Bugs
```suggestion
Correções de *Bugs*
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +Apenas o lançamento mais recente vai receber correções de bugs.
```suggestion
Apenas o lançamento mais recente vai receber correções de *bugs*.
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +Quando bugs o suficiente forem corrigidos e é considerado que vale a pena lançar uma nova gem, essa é a branch em que isso acontece.
```suggestion
Quando *bugs* o suficiente forem corrigidos e é considerado que vale a pena lançar uma nova *gem*, essa é a *branch* de que isso acontece.
```

Acho que aqui a tradução seria mais da origem que a release vai ser lançada então fiz uma pequena sugestão no final mas acho que estava bem legal desde do inicio, então não é totalmente necessária

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
```suggestion
```

Acho que aqui ficou um espaço a mais que fez o git ficar um pouco estranho.

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +Apenas *patches* de seguranças diretos serão incluídos em lançamentos de segurança. Correções para bugs que não são relacionados à segudança que resultam de um *patch* de segurança podem ser publicad
```suggestion
Apenas *patches* de seguranças diretos serão incluídos em lançamentos de segurança. Correções para bugs que não são relacionados à segurança que resultam de um *patch* de segurança podem ser publicados na branch x-y-stable de um lançamento, e será lançado apenas em uma nova gem de acordo com a política de Correção de Bugs.
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
> +
```suggestion
```

2022-10-01 17:57 UTC, HenriqueMorato commented on pt-BR/maintenance_policy.md
```suggestion
```

2022-10-01 18:17 UTC, tomascco requested changes
🥇

2022-10-01 18:17 UTC, tomascco commented on pt-BR/maintenance_policy.md
> +Para problemas crítico de segurança, todos os lançamentos que estão na versão *major* atual, e o último release na versão *major* anterior, vão receber patches e novas versões. A classificação do pro
```suggestion
Para problemas críticos de segurança, todos os lançamentos que estão na versão *major* atual, e o último release na versão *major* anterior, vão receber patches e novas versões. A classificação do problema de segurança é julgado pelo time *core*.
```

2022-10-01 18:45 UTC, laurasantiagocm commented on pt-BR/maintenance_policy.md
> +***Patch* `Z`**
boa! Vou alterar.

2022-10-01 20:15 UTC, HenriqueMorato approved these changes
🚀

2022-10-07 02:24 UTC, tkusuki approved these changes
Mais uma excelente contribuição @laurasantiagocm ! :tada: 

Fiz apenas algumas sugestões, mas nada impeditivo para o merge do PR.
Já deixo aqui o meu approve :+1:

2022-10-07 02:24 UTC, tkusuki commented on pt-BR/maintenance_policy.md
> +O suporte do framework Rails é dividido em quatro grupos: Novas funcionalidades, correções de bug, problemas de segurança e problemas críticos de segurança. Eles são manuseados como exemplificado a s
```suggestion
O suporte do _framework_ Rails é dividido em quatro grupos: novas funcionalidades, correções de bug, problemas de segurança e problemas críticos de segurança. Eles são manuseados como exemplificado a seguir, todas versões, exceto lançamentos de segurança, em formato `X.Y.Z`.
```

2022-10-07 02:24 UTC, tkusuki commented on pt-BR/maintenance_policy.md
> +Novas funcionalidades são adicionadas apenas na branch principal e não estarão disponíveis em lançamentos pontuais.
```suggestion
Novas funcionalidades são adicionadas apenas na _branch_ principal e não estarão disponíveis em lançamentos pontuais.
```

2022-10-07 02:24 UTC, tkusuki commented on pt-BR/maintenance_policy.md
> +Esses lançamentos são criados utilizando a última versão lançada, aplicando as *patches* de segurança e lançando. Esses *patches* são, então, aplicados no fim da branch x-y-stable. Por exemplo, um la
```suggestion
Esses lançamentos são criados utilizando a última versão lançada, aplicando as *patches* de segurança e lançando. Esses *patches* são, então, aplicados no fim da _branch_ x-y-stable. Por exemplo, um lançamento de segurança teórico 1.2.2.1 seria construído a partir da 1.2.2 e, depois, adicionado no fim da 1-2-stable. Isso significa que lançamentos de segurança são fáceis de atualizar se você usar a versão mais recente do Rails.
```

2022-10-07 02:24 UTC, tkusuki commented on pt-BR/maintenance_policy.md
> +Apenas *patches* de seguranças diretos serão incluídos em lançamentos de segurança. Correções para *bugs* que não são relacionados à segurança que resultam de um *patch* de segurança podem ser public
```suggestion
Apenas *patches* de seguranças diretos serão incluídos em lançamentos de segurança. Correções para *bugs* que não são relacionados à segurança que resultam de um *patch* de segurança podem ser publicados na _branch_ x-y-stable de um lançamento, e será lançado apenas em uma nova *gem* de acordo com a política de Correção de *Bugs*.
```

2022-10-07 02:24 UTC, tkusuki commented on pt-BR/maintenance_policy.md
> +Para problemas críticos de segurança, todos os lançamentos que estão na versão *major* atual, e o último release na versão *major* anterior, vão receber patches e novas versões. A classificação do pr
```suggestion
Para problemas críticos de segurança, todos os lançamentos que estão na versão *major* atual, e o último _release_ na versão *major* anterior, vão receber patches e novas versões. A classificação do problema de segurança é avaliado pelo time *core*.
```

2022-10-08 18:36 UTC, laurasantiagocm commented
boa! obrigada <3 fico feliz de poder contribuir!

2022-10-10 14:38 UTC, merged