Traduzir Security >4.1 Redirection and Files
campuscode/rails-guides-pt-BR pull request #815
Opened 2022-10-30 20:51 UTC by vinibispo

## Motivação

Tradução do tópico  **4 Redirection and Files** da página **Security**.

## Comentários

*Coloque comentários que considerar importante mencionar*

Exemplo:

https://guides.rubyonrails.org/security.html#redirection-and-files

Traduzi apenas o primeiro parágrafo do tópico.

2022-11-24 13:18 UTC, HenriqueMorato reviewed
Parabéns pela contribuição, fiz alguns comentários simples e tentei deixar a sugestão para simplificar. Pode dar uma olhada o que acha?

2022-11-24 13:18 UTC, HenriqueMorato commented on pt-BR/security.md
> +Quando quer que o usuário é permitido passar (partes de) a URL para redirecionamento, é possívelmente vulnerável. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que p
```suggestion
Quando quer que o usuário é permitido passar (partes de) a URL para redirecionamento, é possivelmente vulnerável. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que parece exatamente com a original. Isso também chamado de ataque de _phishing_ funciona por enviar um link não malicioso em um email para os usuários, injetando o link por _XSS_ na aplicação web ou colocando o link em um site externo. É não-suspeito, porque o link começa com a URL da aplicação web e a URL para o site malicioso é escondida no parâmetro de redirecionamento: http://www.example.com/site/redirect?to=www.attacker.com. Aqui está um exemplo com uma ação legada:
```

2022-11-24 13:18 UTC, HenriqueMorato commented on pt-BR/security.md
> +def legada
```suggestion
def legacy
```

Normalmente não traduzimos código por ser mais comum na comunidade Rails os códigos serem em inglês. O que acha?

2023-02-17 17:37 UTC, bragamat requested changes
Acredito que tem alguns errinhos ai! acho que depois de resolvido já podemos mergear 😄

2023-02-17 17:37 UTC, bragamat commented on pt-BR/security.md
> +Se é no fim da URL, isso dificilmente será notado e redireciona o usuário para o _host_ `attacker.com`. Como uma regra geral, passar entradas de usuário diretamente no `redirect_to` é considerado per
Acho que tem um parenteses faltando aqui.
```suggestion
Se é no fim da URL, isso dificilmente será notado e redireciona o usuário para o _host_ `attacker.com`. Como uma regra geral, passar entradas de usuário diretamente no `redirect_to` é considerado perigoso. Uma contramedida simple seria _incluir apenas os parâmetros esperados em uma ação legada. (novamente uma abordagem de lista permitida, ao invés de remover parâmetros inesperados). E se você redirecionar para uma URL, cheque com uma lista permitida ou uma expressão regular.
```

2023-02-17 17:37 UTC, bragamat commented on pt-BR/security.md
> +Quando quer que o usuário é permitido passar (partes de) a URL para redirecionamento, é possivelmente vulnerável. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que p
```suggestion
Quando o usuário é permitido passar a (ou partes de uma) URL para redirecionamento, é passível de vulnerábilidades. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que parece exatamente com a original. Isso também chamado de ataque de _phishing_ funciona por enviar um link não malicioso em um email para os usuários, injetando o link por _XSS_ na aplicação web ou colocando o link em um site externo. É não-suspeito, porque o link começa com a URL da aplicação web e a URL para o site malicioso é escondida no parâmetro de redirecionamento: http://www.example.com/site/redirect?to=www.attacker.com. Aqui está um exemplo com uma ação legada:
```

2023-05-06 01:04 UTC, Auralcat commented on pt-BR/security.md
> +Outra classe de vulnerabilidades de securanças envolve o uso de redirecionamento e arquivos em aplicações web.
```suggestion
Outra classe de vulnerabilidades de seguranças envolve o uso de redirecionamento e arquivos em aplicações web.
```

Achei um typo, você poderia olhar por favor? :)

2023-05-10 12:28 UTC, Auralcat commented on pt-BR/security.md
> +Quando o usuário é permitido passar a (ou partes de uma) URL para redirecionamento, é passível de vulnerábilidades. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que
```suggestion
Quando o usuário é permitido passar a (ou partes de uma) URL para redirecionamento, é passível de vulnerabilidades. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que parece exatamente com a original. Isso também chamado de ataque de _phishing_ funciona por enviar um link não malicioso em um email para os usuários, injetando o link por _XSS_ na aplicação web ou colocando o link em um site externo. É não-suspeito, porque o link começa com a URL da aplicação web e a URL para o site malicioso é escondida no parâmetro de redirecionamento: http://www.example.com/site/redirect?to=www.attacker.com. Aqui está um exemplo com uma ação legada:
```

2023-05-10 12:30 UTC, Auralcat commented on pt-BR/security.md
> +Quando o usuário é permitido passar a (ou partes de uma) URL para redirecionamento, é passível de vulnerábilidades. O ataque mais óbvio seria redirecionar os usuários para uma aplicação web falsa que
Outro ponto: acho que podemos traduzir `unsuspecting` nesse caso como `malicioso`, já que o vetor dos ataques de phishing são links que parecem inofensivos mas apontam para sites maliciosos. Me parece a maneira mais direta de traduzir. 

O que vc acha?

2023-05-23 12:51 UTC, merged