WIP: Tradução Ruby on Rails Guides Guidelines > Markdown
campuscode/rails-guides-pt-BR pull request #824
Opened 2023-02-17 01:33 UTC by Biancamazzi

Close: [823](https://github.com/campuscode/rails-guides-pt-BR/issues/823)

## Motivação

*Descreva as motivações deste PR*

Exemplo:

Tradução do tópico  **Markdown** da página **Ruby on Rails Guides Guidelines**.

2023-02-17 17:27 UTC, bragamat requested changes

2023-02-17 17:27 UTC, bragamat commented on pt-BR/ruby_on_rails_guides_guidelines.md
> +Esse guia apresenta orientações para escrever Ruby on Rails guias. Esse guia serve por si só como exemplo.
acho que aqui soa melhor com `guia` antes.  O que você acha ? 😄 
```suggestion
Esse guia apresenta orientações para escrever guias Ruby on Rails. Esse guia serve por si só como exemplo.
```

2023-02-20 22:58 UTC, bragamat approved these changes
Boa!!

2023-02-20 23:00 UTC, bragamat commented
@HenriqueMorato @akaninja Conseguimos um merge aqui ? 😄

2023-02-22 17:05 UTC, AllanSiqueira approved these changes
@Biancamazzi Parabéns pela sua primeira contribuição! Seja bem vinda!

2023-02-22 19:10 UTC, merged